name: Android CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      # ⬇️ ZAWSZE generujemy wrapper 8.7 (nawet jeśli był jakiś pseudo-wrapper)
      - name: Force Gradle Wrapper 8.7
        run: |
          sudo apt-get update && sudo apt-get install -y gradle
          rm -rf gradle gradlew gradlew.bat
          gradle wrapper --gradle-version 8.7 --distribution-type all
          chmod +x gradlew

      # ⬇️ Pobierz AAR Nothing do app/libs (nie trzeba trzymać w repo)
      - name: Fetch Nothing Glyph Matrix SDK (AAR)
        run: |
          mkdir -p app/libs
          curl -L https://raw.githubusercontent.com/Nothing-Developer-Programme/GlyphMatrix-Development-Kit/main/glyph-matrix-sdk-1.0.aar -o app/libs/glyph-matrix-sdk-1.0.aar
          ls -la app/libs

      - name: Cache Gradle
        uses: gradle/gradle-build-action@v3

      - name: Assemble Debug
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: wolf-apk
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload build logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-logs
          path: '**/*.log'
